language: node_js
node_js:
  - 0.10
env:
  - DISPLAY=:99.0
before_script:
  - sh -e /etc/init.d/xvfb start
after_failure:
  - echo 'Uploading result of integration test to clbin.com'
  - cat build/tests/github.xhtml | curl -F 'clbin=<-' https://clbin.com
deploy:
  provider: npm
  email: christoph.burgmer@gmail.com
  api_key:
    secure: CrI/JbhMreN61esr3vvf1c3O+CHVbNPAR5VXWebBC6ANGwZXQH6LZ5EH97NF4CZ+sJc12AmAKm29bFOf5rwIvP++VDoxA5mOvtx0xxOwlMHdKFwfglfLxztQpUAlqMz5Nci9u9kO5d3eBPgaeUzz0ye6tsX+en9aOfBKBljl85o=
  on:
    tags: true
    repo: cburgmer/inlineresources
    # Change when this is fixed: https://github.com/travis-ci/travis-ci/issues/1675
    all_branches: true
