language: node_js
node_js:
  - 0.10
env:
  - DISPLAY=:99.0
before_script:
  - sh -e /etc/init.d/xvfb start
after_failure:
  - echo 'Uploading result of integration test to clbin.com'
  - cat build/tests/github.xhtml | curl -F 'clbin=<-' https://clbin.com
deploy:
  provider: npm
  email: christoph.burgmer@gmail.com
  api_key:
    secure: S5+jClyW9k9Npqhn5vt/KMUOj0dFnEma/C6rDqMo4Z9gI3jhfCEJyCWcAyXWARR9cA9OzcR/U8+lBav7jivPJR4Ois3TyNx0CcKAP7zCy9lIoUypuKA8XbYA4HUiXTLesV2D/Qr2F7fUDph1duTr6QJKnRtFSHZGjMkhyRjGjjI=
  on:
    tags: true
    repo: cburgmer/inlineresources
    # Change when this is fixed: https://github.com/travis-ci/travis-ci/issues/1675
    all_branches: true
